### ISSUE TITLE
Decide on fonts

### ISSUE THREAD

**Issue by stephband** [cazjack/cazjack.github.com#5]
I forgot to ask if you'd thought about fonts?

Helvetica, as it is now, is fine, I suppose. It's certainly fast because everybody has it already, so the browser does not need to download it with the page.

But have a look at fonts.google.com for ideas. Those are free web fonts. (There are also a whole load of paid for fonts available as web fonts from various places. We make swisstypefaces.com, for example.)

I have a feeling your site might be nice with a serif font for paragraph text. Serifs make text very readable. Then maybe a matching sans-serif for titles. Maybe a pair like 'Source Serif Pro' and 'Source Sans Pro' together. But it's just a thought, and you might find that idea too 'classic'.

**Comment by cazjack** [comment]
thank you, will have a look 👍

**Comment by stephband** [comment]
I chose Source Sans and Source Serif for body text. Let me know if you like, closing for now.
