### ISSUE TITLE
header

### ISSUE THREAD

**Issue by cazjack** [cazjack/cazjack.github.com#7]
just a question about spacing of the header, on the index page its in line with podium I am speaking at, when looking at the About page, its above the podium.  but the code looks the same.

screengrab of index: 
![image](https://github.com/cazjack/cazjack.github.com/assets/133686783/f9bd0171-52ed-40d6-8ea3-c29dcca17779)
screengrab of About
![image](https://github.com/cazjack/cazjack.github.com/assets/133686783/54610554-ae04-45a7-961c-3e8a169d1bab)

**Comment by stephband** [comment]
Yes, there was one class missing in about and some other pages: "y-end", which effectively aligns the text to the lower padding of the header. I'm going to add navigation to the header now, so probably will have to rejig things anyway
