### ISSUE TITLE
index page

### ISSUE THREAD

**Issue by cazjack** [cazjack/cazjack.github.com#9]
Hiya
I made some small amends to the text on the Index page yesterday, these appear in html but not on the front event

<img width="960" alt="Screenshot 2023-06-05 12 45 43" src="https://github.com/cazjack/cazjack.github.com/assets/133686783/e0d94a3a-68bf-4fe1-9608-54846b3134b6">
<img width="960" alt="Screenshot 2023-06-05 12 47 02" src="https://github.com/cazjack/cazjack.github.com/assets/133686783/f86a59a6-4122-4a09-961a-bd47e8444c4e">

**Comment by stephband** [comment]
Hmmm whats going on, not seeing my changes either...

**Comment by stephband** [comment]
Ooooooh. Bad stuff.

<img width="1430" alt="Screenshot 2023-06-12 at 07 21 10" src="https://github.com/cazjack/cazjack.github.com/assets/69022/2e7b8dbc-9321-4637-b7de-05b1f418f0b2">

**Comment by stephband** [comment]
Okay, fixed, site should build and deploy automatically again.
